"""fixed user agent column name

Revision ID: 01441d9529c0
Revises: ba27f244d7be
Create Date: 2025-11-23 11:34:28.160941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01441d9529c0'
down_revision: Union[str, Sequence[str], None] = 'ba27f244d7be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_login_user_agent', sa.Text(), nullable=True))
        batch_op.drop_column('last_login_user')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_login_user', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('last_login_user_agent')

    # ### end Alembic commands ###
