"""Add PR management tables

Revision ID: 164f58140f5e
Revises: f0f73a801d78
Create Date: 2025-12-14 15:46:42.910287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '164f58140f5e'
down_revision: Union[str, Sequence[str], None] = 'f0f73a801d78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('github_tokens',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('repository_owner', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('repository_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('repository_full', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
    sa.Column('is_encrypted', sa.Boolean(), nullable=False),
    sa.Column('token_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('scopes', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('permissions_json', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('github_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_github_tokens_repository_full'), ['repository_full'], unique=True)
        batch_op.create_index(batch_op.f('ix_github_tokens_repository_name'), ['repository_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_github_tokens_repository_owner'), ['repository_owner'], unique=False)

    op.create_table('pr_creation_logs',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('incident_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('pr_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.Column('repository_full', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('branch_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('failure_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('root_cause', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('files_to_change', sa.Integer(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('pr_url', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('extra_metadata', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pr_creation_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pr_creation_logs_incident_id'), ['incident_id'], unique=False)

    op.create_table('pull_requests',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('incident_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('repository_owner', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('repository_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('repository_full', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('pr_number', sa.Integer(), nullable=False),
    sa.Column('pr_url', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('branch_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('base_branch', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('CREATED', 'OPEN', 'DRAFT', 'REVIEW_REQUESTED', 'APPROVED', 'MERGED', 'CLOSED', 'FAILED', name='prstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('merged_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('files_changed', sa.Integer(), nullable=True),
    sa.Column('additions', sa.Integer(), nullable=True),
    sa.Column('deletions', sa.Integer(), nullable=True),
    sa.Column('commits_count', sa.Integer(), nullable=True),
    sa.Column('approved_by', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('review_comments_count', sa.Integer(), nullable=False),
    sa.Column('has_conflicts', sa.Boolean(), nullable=False),
    sa.Column('failure_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('root_cause', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('extra_metadata', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pull_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pull_requests_incident_id'), ['incident_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pull_requests_repository_name'), ['repository_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_pull_requests_repository_owner'), ['repository_owner'], unique=False)

    # NOTE: user_details and ivfflat index operations skipped
    # user_details table already exists, and ivfflat index cannot support 4096 dimensions
    # These changes will be handled separately if needed

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.create_table('user_details',
    sa.Column('user_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('country', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('postal_code', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('facebook_link', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('twitter_link', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('linkedin_link', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('instagram_link', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('github_link', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('user_details_user_id_fkey')),
    sa.PrimaryKeyConstraint('user_id', name=op.f('user_details_pkey'))
    )
    with op.batch_alter_table('user_details', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_user_details_country_city'), ['country', 'city'], unique=False)

    with op.batch_alter_table('pull_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pull_requests_repository_owner'))
        batch_op.drop_index(batch_op.f('ix_pull_requests_repository_name'))
        batch_op.drop_index(batch_op.f('ix_pull_requests_incident_id'))

    op.drop_table('pull_requests')
    with op.batch_alter_table('pr_creation_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pr_creation_logs_incident_id'))

    op.drop_table('pr_creation_logs')
    with op.batch_alter_table('github_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_github_tokens_repository_owner'))
        batch_op.drop_index(batch_op.f('ix_github_tokens_repository_name'))
        batch_op.drop_index(batch_op.f('ix_github_tokens_repository_full'))

    op.drop_table('github_tokens')
    # ### end Alembic commands ###
