"""remove_github_secrets_from_users

Revision ID: 4a40d469c89a
Revises: 93799c77955a
Create Date: 2025-11-25 14:01:12.960889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4a40d469c89a'
down_revision: Union[str, Sequence[str], None] = '93799c77955a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('github_webhook_secret', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('github_username', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('github_username')
        batch_op.drop_column('github_webhook_secret')

    # ### end Alembic commands ###
