"""initial schema - all tables

Revision ID: 65589c7f67a3
Revises: 
Create Date: 2025-11-09 13:06:02.905903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector

# revision identifiers, used by Alembic.
revision: str = '65589c7f67a3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('config',
    sa.Column('config_key', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('config_value', sa.Text(), nullable=True),
    sa.Column('value_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('is_secret', sa.Boolean(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('config_key')
    )
    with op.batch_alter_table('config', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_config_category'), ['category'], unique=False)

    op.create_table('incidents',
    sa.Column('incident_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('severity', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('failure_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('error_log', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('stack_trace', sa.Text(), nullable=True),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('fixability', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('similar_incidents', sa.JSON(), nullable=True),
    sa.Column('remediation_plan', sa.JSON(), nullable=True),
    sa.Column('remediation_executed', sa.Boolean(), nullable=False),
    sa.Column('remediation_start_time', sa.DateTime(), nullable=True),
    sa.Column('remediation_end_time', sa.DateTime(), nullable=True),
    sa.Column('outcome', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('outcome_message', sa.Text(), nullable=True),
    sa.Column('resolution_time_seconds', sa.Integer(), nullable=True),
    sa.Column('human_feedback', sa.JSON(), nullable=True),
    sa.Column('approved_by', sa.Text(), nullable=True),
    sa.Column('approval_timestamp', sa.DateTime(), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('incident_id')
    )
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.create_index('idx_incidents_confidence_desc', [sa.literal_column('confidence DESC')], unique=False)
        batch_op.create_index('idx_incidents_outcome_created', ['outcome', 'created_at'], unique=False)
        batch_op.create_index('idx_incidents_source_severity', ['source', 'severity'], unique=False)
        batch_op.create_index('idx_incidents_timestamp_desc', [sa.literal_column('timestamp DESC')], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_confidence'), ['confidence'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_failure_type'), ['failure_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_outcome'), ['outcome'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_resolved_at'), ['resolved_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_timestamp'), ['timestamp'], unique=False)

    op.create_table('metrics',
    sa.Column('metric_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('metric_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('metric_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('labels', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('metric_id')
    )
    with op.batch_alter_table('metrics', schema=None) as batch_op:
        batch_op.create_index('idx_metrics_name_timestamp', ['metric_name', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_metrics_metric_name'), ['metric_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_metrics_timestamp'), ['timestamp'], unique=False)

    op.create_table('feedback',
    sa.Column('feedback_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('incident_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('helpful', sa.Boolean(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('user', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('user_email', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('categories', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.incident_id'], ),
    sa.PrimaryKeyConstraint('feedback_id')
    )
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.create_index('idx_feedback_helpful', ['helpful'], unique=False)
        batch_op.create_index('idx_feedback_incident_created', ['incident_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_helpful'), ['helpful'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_incident_id'), ['incident_id'], unique=False)

    op.create_table('remediation_history',
    sa.Column('history_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('incident_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('action_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('executed_at', sa.DateTime(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('outcome', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('executed_by', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('environment', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('dry_run', sa.Boolean(), nullable=False),
    sa.Column('actions_performed', sa.JSON(), nullable=True),
    sa.Column('pre_validation_passed', sa.Boolean(), nullable=False),
    sa.Column('post_validation_passed', sa.Boolean(), nullable=False),
    sa.Column('validation_details', sa.JSON(), nullable=True),
    sa.Column('rollback_required', sa.Boolean(), nullable=False),
    sa.Column('rollback_performed', sa.Boolean(), nullable=False),
    sa.Column('rollback_snapshot_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('execution_logs', sa.JSON(), nullable=True),
    sa.Column('remediation_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.incident_id'], ),
    sa.PrimaryKeyConstraint('history_id')
    )
    with op.batch_alter_table('remediation_history', schema=None) as batch_op:
        batch_op.create_index('idx_remediation_incident_attempt', ['incident_id', 'attempt_number'], unique=False)
        batch_op.create_index('idx_remediation_success_executed', ['success', 'executed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_remediation_history_attempt_number'), ['attempt_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_remediation_history_executed_at'), ['executed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_remediation_history_incident_id'), ['incident_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_remediation_history_success'), ['success'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_vectors',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=3), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('test_vectors_pkey'))
    )
    with op.batch_alter_table('remediation_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_remediation_history_success'))
        batch_op.drop_index(batch_op.f('ix_remediation_history_incident_id'))
        batch_op.drop_index(batch_op.f('ix_remediation_history_executed_at'))
        batch_op.drop_index(batch_op.f('ix_remediation_history_attempt_number'))
        batch_op.drop_index('idx_remediation_success_executed')
        batch_op.drop_index('idx_remediation_incident_attempt')

    op.drop_table('remediation_history')
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feedback_incident_id'))
        batch_op.drop_index(batch_op.f('ix_feedback_helpful'))
        batch_op.drop_index(batch_op.f('ix_feedback_created_at'))
        batch_op.drop_index('idx_feedback_incident_created')
        batch_op.drop_index('idx_feedback_helpful')

    op.drop_table('feedback')
    with op.batch_alter_table('metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_metrics_timestamp'))
        batch_op.drop_index(batch_op.f('ix_metrics_metric_name'))
        batch_op.drop_index('idx_metrics_name_timestamp')

    op.drop_table('metrics')
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incidents_timestamp'))
        batch_op.drop_index(batch_op.f('ix_incidents_source'))
        batch_op.drop_index(batch_op.f('ix_incidents_severity'))
        batch_op.drop_index(batch_op.f('ix_incidents_resolved_at'))
        batch_op.drop_index(batch_op.f('ix_incidents_outcome'))
        batch_op.drop_index(batch_op.f('ix_incidents_failure_type'))
        batch_op.drop_index(batch_op.f('ix_incidents_created_at'))
        batch_op.drop_index(batch_op.f('ix_incidents_confidence'))
        batch_op.drop_index('idx_incidents_timestamp_desc')
        batch_op.drop_index('idx_incidents_source_severity')
        batch_op.drop_index('idx_incidents_outcome_created')
        batch_op.drop_index('idx_incidents_confidence_desc')

    op.drop_table('incidents')
    with op.batch_alter_table('config', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_config_category'))

    op.drop_table('config')
    # ### end Alembic commands ###
