"""added user_details table

Revision ID: 7534e5173df0
Revises: f0f73a801d78
Create Date: 2025-12-13 15:41:26.841681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7534e5173df0'
down_revision: Union[str, Sequence[str], None] = 'f0f73a801d78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_details',
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('postal_code', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('facebook_link', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('twitter_link', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('linkedin_link', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('instagram_link', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('github_link', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    with op.batch_alter_table('user_details', schema=None) as batch_op:
        batch_op.create_index('idx_user_details_country_city', ['country', 'city'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_details', schema=None) as batch_op:
        batch_op.drop_index('idx_user_details_country_city')

    op.drop_table('user_details')
    # ### end Alembic commands ###
