"""updated user_id length

Revision ID: 922939bee4cb
Revises: a079333d6a2b
Create Date: 2025-12-15 15:01:13.936023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '922939bee4cb'
down_revision: Union[str, Sequence[str], None] = 'a079333d6a2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('github_tokens', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(length=36),
               type_=sqlmodel.sql.sqltypes.AutoString(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('github_tokens', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=255),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)

    # ### end Alembic commands ###
