"""Add user_id to github_tokens

Revision ID: a079333d6a2b
Revises: 7d1ffddce18c
Create Date: 2025-12-15 14:32:39.457724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'a079333d6a2b'
down_revision: Union[str, Sequence[str], None] = '7d1ffddce18c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('github_tokens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False))
        batch_op.drop_index(batch_op.f('ix_github_tokens_repository_full'))
        batch_op.create_index(batch_op.f('ix_github_tokens_repository_full'), ['repository_full'], unique=False)
        batch_op.create_index(batch_op.f('ix_github_tokens_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['user_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('github_tokens', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_github_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_github_tokens_repository_full'))
        batch_op.create_index(batch_op.f('ix_github_tokens_repository_full'), ['repository_full'], unique=True)
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
