"""add vector index on embeddings

Revision ID: b1dd7fdd5f08
Revises: 65589c7f67a3
Create Date: 2025-11-16 10:16:50.310506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1dd7fdd5f08'
down_revision: Union[str, Sequence[str], None] = '65589c7f67a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.create_index('idx_incidents_embeddings_ivfflat', ['embedding'], unique=False, postgresql_using='ivfflat', postgresql_with={'lists': 100}, postgresql_ops={'embedding': 'vector_cosine_ops'})

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.drop_index('idx_incidents_embeddings_ivfflat', postgresql_using='ivfflat', postgresql_with={'lists': 100}, postgresql_ops={'embedding': 'vector_cosine_ops'})

    # ### end Alembic commands ###
