"""fixed typo in user table

Revision ID: ba27f244d7be
Revises: c235f7ef9dd5
Create Date: 2025-11-23 11:32:48.598654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ba27f244d7be'
down_revision: Union[str, Sequence[str], None] = 'c235f7ef9dd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('locked_until', sa.DateTime(), nullable=True))
        batch_op.drop_column('locked_util')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('locked_util', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_column('locked_until')

    # ### end Alembic commands ###
