"""oauth login added

Revision ID: d38d004f24bf
Revises: 922939bee4cb
Create Date: 2025-12-26 20:49:23.963485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd38d004f24bf'
down_revision: Union[str, Sequence[str], None] = '922939bee4cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.create_index('idx_incidents_embeddings_ivfflat', ['embedding'], unique=False, postgresql_using='ivfflat', postgresql_with={'lists': 100}, postgresql_ops={'embedding': 'vector_cosine_ops'})

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('oauth_provider', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
        batch_op.add_column(sa.Column('oauth_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
        batch_op.create_index('idx_users_oauth', ['oauth_provider', 'oauth_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_oauth_id'), ['oauth_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_oauth_provider'), ['oauth_provider'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_oauth_provider'))
        batch_op.drop_index(batch_op.f('ix_users_oauth_id'))
        batch_op.drop_index('idx_users_oauth')
        batch_op.drop_column('oauth_id')
        batch_op.drop_column('oauth_provider')

    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.drop_index('idx_incidents_embeddings_ivfflat', postgresql_using='ivfflat', postgresql_with={'lists': 100}, postgresql_ops={'embedding': 'vector_cosine_ops'})

    # ### end Alembic commands ###
